services:
  mysql:
    image: mysql:8.4
    container_name: project_mysql
    environment:
      MYSQL_DATABASE: project_gtvt
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: maven:3.9-eclipse-temurin-17
    container_name: project_app
    working_dir: /app
    command: mvn -DskipTests spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_gtvt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_THYMELEAF_PREFIX: file:/app/src/main/resources/templates/
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: file:/app/src/main/resources/static/
    volumes:
      - ..:/app
      - maven_cache:/root/.m2
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy


  adminer:
    image: adminer:4
    container_name: project_adminer
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  maven_cache:
